"""Convert a Quake Live ``cvarlist`` / ``cmdlist`` dump into a Python catalog.

Run inside the app once you've captured the output:

    cvarlist   -> save to cvarlist.txt
    cmdlist    -> save to cmdlist.txt

Then:

    uv run python tools/import_cvarlist.py cvarlist.txt cmdlist.txt

It writes ``src/ql_console/_generated.py`` which commands.py picks up
automatically (curated descriptions still win for known names).

The cvarlist parser expects lines like ``<flags> <name> "<value>"`` and the
cmdlist parser expects one command name per line. Both tolerate header/footer
lines such as "1234 total cvars".
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

# <optional flag columns> <name> "<current value>"  (value may be empty)
_CVAR_RE = re.compile(r'^(?:.*\s)?(\S+)\s+"([^"]*)"')
# A bare command name on its own line.
_CMD_RE = re.compile(r"^([A-Za-z_][\w]*)\s*$")
# Footer/summary lines to ignore.
_SKIP_RE = re.compile(r"\b(total cvars|cvars|commands)\b", re.IGNORECASE)
# Cvars whose VALUE is sensitive — keep the name, never write the value.
_SECRET_RE = re.compile(r"pass(word|wd)?|secret", re.IGNORECASE)
# Transient per-client junk cvars not worth completing.
_JUNK_RE = re.compile(r"^session\d*$", re.IGNORECASE)

_OUT = Path(__file__).resolve().parents[1] / "src" / "ql_console" / "_generated.py"


def parse_cvars(text: str) -> list[tuple[str, str]]:
    out: list[tuple[str, str]] = []
    seen: set[str] = set()
    for raw in text.splitlines():
        line = raw.strip()
        if not line or _SKIP_RE.search(line):
            continue
        m = _CVAR_RE.match(line)
        if not m:
            continue
        name, value = m.group(1), m.group(2)
        if name in seen or _JUNK_RE.match(name):
            continue
        seen.add(name)
        if _SECRET_RE.search(name):
            value = ""  # redact: never bake secrets into the repo
        desc = f'= "{value}"' if value else ""
        out.append((name, desc))
    return out


def parse_cmds(text: str) -> list[tuple[str, str]]:
    out: list[tuple[str, str]] = []
    seen: set[str] = set()
    for raw in text.splitlines():
        line = raw.strip()
        if not line or _SKIP_RE.search(line):
            continue
        m = _CMD_RE.match(line)
        if not m:
            continue
        name = m.group(1)
        if name in seen:
            continue
        seen.add(name)
        out.append((name, ""))
    return out


def _render(name: str, items: list[tuple[str, str]]) -> str:
    lines = [f"{name} = ["]
    for n, d in items:
        lines.append(f"    ({n!r}, {d!r}),")
    lines.append("]")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    if not argv:
        print(__doc__)
        return 1
    cvars: list[tuple[str, str]] = []
    cmds: list[tuple[str, str]] = []
    for arg in argv:
        text = Path(arg).read_text(encoding="utf-8", errors="replace")
        # Heuristic: a file with quoted values is a cvarlist; otherwise cmdlist.
        if '"' in text:
            cvars.extend(parse_cvars(text))
        else:
            cmds.extend(parse_cmds(text))

    header = '"""Auto-generated by tools/import_cvarlist.py. Do not edit by hand."""\n\n'
    body = _render("GENERATED_CVARS", cvars) + "\n\n" + _render("GENERATED_CMDS", cmds) + "\n"
    _OUT.write_text(header + body, encoding="utf-8")
    print(f"Wrote {_OUT} — {len(cvars)} cvars, {len(cmds)} commands.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
